### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by comtihon** [burningalchemist/minikube-ny#1]
Hi, I tried to run the appliation, as it said in the readme:
`cd minikube-ny/misc/ansible && ansible-playbook minikube.yml -vv`
It failed in my case on `common : Installing Homebrew Cask Packages`.
For some reason it tries to install docker, but it is installed.
The stack trace:
```
TASK [common : Installing Homebrew Cask Packages] ******************************
task path: /Users/vtikhonov/minikube-ny/misc/ansible/roles/common/tasks/main.yml:26
Password:
failed: [localhost] (item=docker) => {"changed": false, "item": "docker", "msg": "Error: It seems there is already an App at '/Applications/Docker.app'."}
changed: [localhost] => (item=minikube) => {"changed": true, "item": "minikube", "msg": "Cask installed: minikube"}
	to retry, use: --limit @/Users/vtikhonov/minikube-ny/misc/ansible/minikube.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1 
```

**Comment by burningalchemist** [comment]
Hi!

The error exists because the Docker was installed before not with a homebrew, but presumably directly via dmg package, so it can't be replaced.

You probably have installed Docker for Mac before as dmg package directly, so it doesn’t have those components to share between the other applications. Usually when the cask is already installed, we have an exit code 0 and don’t consider it as an error. It's not that easy to manage mixed environments.

So the easiest way would be to let Docker be installed with a homebrew or just comment it out from `roles/common/defaults/main.yml`, if current setup contains important data. In this case, the playbook will install missing dependencies to let the installation run properly.

Thank you! :)
